/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:85807edd-88a0-4ffd-b2a1-3b7aa5c50fbf",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_D26i3NNmH",
    "aws_user_pools_web_client_id": "31q5o8mlc39ca5oec13e85jcjd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "backend",
            "endpoint": "https://sv4w6pff3g.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        },
        {
            "name": "apie2a152f1",
            "endpoint": "https://jaa2su82ra.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Camera-dev",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Device-dev",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "ppaModel-dev",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Deployment-dev",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Event-dev",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
