/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:957e3434-0a09-4215-b453-ce14aca82716",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_l9oPs3boN",
    "aws_user_pools_web_client_id": "3je4uos17tf72rc660m15n3a28",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "backend",
            "endpoint": "https://q3l30j8kgc.execute-api.ap-southeast-1.amazonaws.com/test",
            "region": "ap-southeast-1"
        },
        {
            "name": "apie2a152f1",
            "endpoint": "https://k5fdouqly0.execute-api.ap-southeast-1.amazonaws.com/test",
            "region": "ap-southeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Camera-test",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Device-test",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "ppaModel-test",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Deployment-test",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "Event-test",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
